config/routes.rb
require 'sidekiq/web'

Myapp::Application.routes.draw do

  resources :startups

  mount Sidekiq::Web => '/sidekiq'

end

app/models/startup.rb
class Startup < ActiveRecord::Base
  attr_accessible :blog_feed_url, :blog_url, :category, :city, :country, :details_url, :email, :founding_date, :homepage_url, :linkedin_url, :name, :number_of_employees, :phone, :short_description, :state, :twitter_username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  # GET /startups
  # GET /startups.json
  def index
    @startups = Startup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @startups }
    end
  end

  # GET /startups/1
  # GET /startups/1.json
  def show
    @startup = Startup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @startup }
    end
  end

  # GET /startups/new
  # GET /startups/new.json
  def new
    @startup = Startup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @startup }
    end
  end

  # GET /startups/1/edit
  def edit
    @startup = Startup.find(params[:id])
  end

  # POST /startups
  # POST /startups.json
  def create
    @startup = Startup.new(params[:startup])

    respond_to do |format|
      if @startup.save
        format.html { redirect_to @startup, notice: 'Startup was successfully created.' }
        format.json { render json: @startup, status: :created, location: @startup }
      else
        format.html { render action: "new" }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /startups/1
  # PUT /startups/1.json
  def update
    @startup = Startup.find(params[:id])

    respond_to do |format|
      if @startup.update_attributes(params[:startup])
        format.html { redirect_to @startup, notice: 'Startup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /startups/1
  # DELETE /startups/1.json
  def destroy
    @startup = Startup.find(params[:id])
    @startup.destroy

    respond_to do |format|
      format.html { redirect_to startups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/startups_helper.rb
module StartupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/startups/_form.html.erb
<%= form_for(@startup) do |f| %>
  <% if @startup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@startup.errors.count, "error") %> prohibited this startup from being saved:</h2>

      <ul>
      <% @startup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :short_description %><br />
    <%= f.text_area :short_description %>
  </div>
  <div class="field">
    <%= f.label :details_url %><br />
    <%= f.text_field :details_url %>
  </div>
  <div class="field">
    <%= f.label :homepage_url %><br />
    <%= f.text_field :homepage_url %>
  </div>
  <div class="field">
    <%= f.label :blog_url %><br />
    <%= f.text_field :blog_url %>
  </div>
  <div class="field">
    <%= f.label :blog_feed_url %><br />
    <%= f.text_field :blog_feed_url %>
  </div>
  <div class="field">
    <%= f.label :twitter_username %><br />
    <%= f.text_field :twitter_username %>
  </div>
  <div class="field">
    <%= f.label :number_of_employees %><br />
    <%= f.number_field :number_of_employees %>
  </div>
  <div class="field">
    <%= f.label :linkedin_url %><br />
    <%= f.text_field :linkedin_url %>
  </div>
  <div class="field">
    <%= f.label :founding_date %><br />
    <%= f.date_select :founding_date %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/startups/edit.html.erb
<h1>Editing startup</h1>

<%= render 'form' %>

<%= link_to 'Show', @startup %> |
<%= link_to 'Back', startups_path %>

app/views/startups/index.html.erb
<h1>Listing startups</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Short description</th>
    <th>Details url</th>
    <th>Homepage url</th>
    <th>Blog url</th>
    <th>Blog feed url</th>
    <th>Twitter username</th>
    <th>Number of employees</th>
    <th>Linkedin url</th>
    <th>Founding date</th>
    <th>Country</th>
    <th>City</th>
    <th>State</th>
    <th>Category</th>
    <th>Phone</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @startups.each do |startup| %>
  <tr>
    <td><%= startup.name %></td>
    <td><%= startup.short_description %></td>
    <td><%= startup.details_url %></td>
    <td><%= startup.homepage_url %></td>
    <td><%= startup.blog_url %></td>
    <td><%= startup.blog_feed_url %></td>
    <td><%= startup.twitter_username %></td>
    <td><%= startup.number_of_employees %></td>
    <td><%= startup.linkedin_url %></td>
    <td><%= startup.founding_date %></td>
    <td><%= startup.country %></td>
    <td><%= startup.city %></td>
    <td><%= startup.state %></td>
    <td><%= startup.category %></td>
    <td><%= startup.phone %></td>
    <td><%= startup.email %></td>
    <td><%= link_to 'Show', startup %></td>
    <td><%= link_to 'Edit', edit_startup_path(startup) %></td>
    <td><%= link_to 'Destroy', startup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Startup', new_startup_path %>

app/views/startups/new.html.erb
<h1>New startup</h1>

<%= render 'form' %>

<%= link_to 'Back', startups_path %>

app/views/startups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @startup.name %>
</p>

<p>
  <b>Short description:</b>
  <%= @startup.short_description %>
</p>

<p>
  <b>Details url:</b>
  <%= @startup.details_url %>
</p>

<p>
  <b>Homepage url:</b>
  <%= @startup.homepage_url %>
</p>

<p>
  <b>Blog url:</b>
  <%= @startup.blog_url %>
</p>

<p>
  <b>Blog feed url:</b>
  <%= @startup.blog_feed_url %>
</p>

<p>
  <b>Twitter username:</b>
  <%= @startup.twitter_username %>
</p>

<p>
  <b>Number of employees:</b>
  <%= @startup.number_of_employees %>
</p>

<p>
  <b>Linkedin url:</b>
  <%= @startup.linkedin_url %>
</p>

<p>
  <b>Founding date:</b>
  <%= @startup.founding_date %>
</p>

<p>
  <b>Country:</b>
  <%= @startup.country %>
</p>

<p>
  <b>City:</b>
  <%= @startup.city %>
</p>

<p>
  <b>State:</b>
  <%= @startup.state %>
</p>

<p>
  <b>Category:</b>
  <%= @startup.category %>
</p>

<p>
  <b>Phone:</b>
  <%= @startup.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @startup.email %>
</p>


<%= link_to 'Edit', edit_startup_path(@startup) %> |
<%= link_to 'Back', startups_path %>